
//----------------------------------------------------
// The following code was generated by CUP v0.10i
// Sun Apr 11 11:20:05 EDT 1999
//----------------------------------------------------

package nrc.fuzzy;

/** CUP generated class containing symbol constants. */
public class FuzzyParserSym {
  /* terminals */
  public static final int FUZZYTERM = 7;
  public static final int EOF = 0;
  public static final int OR = 3;
  public static final int error = 1;
  public static final int FUZZYMODIFIER = 6;
  public static final int LPAREN = 4;
  public static final int RPAREN = 5;
  public static final int AND = 2;
}

