/*
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 *  http://mozilla.org/MPL/2.0/. 
 *
 * Copyright 2000, 2001, 2002, 2003, 2004, 2005, 2006 National Research Council of Canada 
 * 
 * This software was initially developed at the National Research Council of Canada (NRC).
 *
 * THE NATIONAL RESEARCH COUNCIL OF CANADA MAKES NO REPRESENTATIONS OR
 * WARRANTIES ABOUT THE SUITABILITY OF THE SOFTWARE, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
 * THE NATIONAL RESEARCH COUNCIL OF CANADA SHALL NOT BE LIABLE FOR ANY DAMAGES
 * SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR DISTRIBUTING
 * THIS SOFTWARE OR ITS DERIVATIVES.
 *
 *
 */

 
package nrc.fuzzy;

import java.io.*;

/**
 * An implementation of the FuzzySetFunction interface to provide
 * a class with the ability to generate a FuzzySet that is an
 * S-shaped curve with membership value 0 on the lower left to 1 on the upper right.
 * This class is typically used when constructing instances of the classes
 * LFuzzySet and LRFuzzySet. The PIFuzzySet for example is constructed using
 * the SFunction to create its left half and the ZFunction to create its
 * right half.
 * <br> <br>
 * The SFunction membership values (y values) are calculated as follows:
 * <br>
 * <code>
 * 
 * 		leftX is the lower left X value 
 * 		rightX is the upper right X value
 * 		midpoint is the x value half way between leftX and rightX
 * 		sqr is the square root function
 * 
 *      if x is <= leftX then y = 0.0
 *      if x is between leftX and the midpoint 
 * 				then y = 2*sqr(((x - leftX)/(rightX - leftX)))
 *      if x is midpoint then y = 0.5
 *      if x is between the midpoint and rightX 
 * 				then y = 1 - 2*sqr(((x - rightX)/(rightX - leftX)))
 *      if x is >= rightX then y = 1.0
 *
 * </code>
 * 
 * @author Bob Orchard
 *
 * @see LFuzzySet
 * @see LRFuzzySet
 * @see PIFuzzySet
 * @see ZFunction
 */
public class SFunction implements FuzzySetFunction, Serializable
{
    /**
     * This value is used to determine the number of points that will be
     * in the S-shaped fuzzy set generated by the 
     * <code>generateFuzzySet(double leftX, double rightX)</code> method,
     * unless it has a value of < 3, in which case the value of static (class)
     * variable, sFunctionDefaultNumPoints, will be used. This allows 
     * each instance of the SFunction to determine its own value for the number
     * of points to be generated. Initially it is set to have the value 0 so
     * that the sFunctionDefaultNumPoints value is used. If the number 
     * is even it will be set to the next higher odd value 
     * (to maintain symmetry for the S curve).
     * 
     */
    int defaultNumPoints = 0;
    
    /**
     * This value is used to determine the number of points that will be
     * in the S-shaped fuzzy set generated by the 
     * <code>generateFuzzySet(double leftX, double rightX)</code> method
     * when the local instance variable defaultNumPoints has not been
     * set or is < 3. Initially it is set to have the value 9. If the number 
     * is even it will be set to the next higher odd value 
     * (to maintain symmetry for the S curve).
     * 
     */
    static int sFunctionDefaultNumPoints;

    /*===============================================
     *
     * CONSTRUCTORS
     *
     *==============================================*/

    /**
     * Creates an instance of an SFunction that is used to generate Fuzzysets
     * with an S-shape. A FuzzySet created will have a 0 value at its left and a 1 value
     * at its right.
     * 
     */
    public SFunction()
    {}

    /**
     * Creates an instance of an SFunction that is used to generate Fuzzysets
     * with an S-shape. A FuzzySet created will have a 0 value at its left and a 1 value
     * at its right. When created with this constructor a value for the number
     * of points to be used when creating the S-shaped fuzzy set is set (defaultNumPoints).
     * 
     * @param numPoints the number of points to use when creating the S-shaped FuzzySet.
     */
    public SFunction(int numPoints)
    {
        setNumPoints(numPoints);
    }
    
    static 
    {
        sFunctionDefaultNumPoints = 9;
    }    

    /*===============================================
     *
     * METHODS
     *
     *==============================================*/

    /**
     * Creates a FuzzySet with an S-shape such that the membership value is
     * 0 at the leftX value and 1 at the rightX value. The number of points in
     * the generated FuzzySet is determined by the settings of the local instance 
     * variable <code>defaultNumPoints</code> and the static class variable 
     * <code>sFunctionDefaultNumPoints</code>.
     *
     * @param leftX  the bottom left x value of the S-shaped curve.
     * @param rightX the upper right x value of the S-shaped curve.
     */
    public FuzzySet generateFuzzySet(double leftX, double rightX)
    {
        if(defaultNumPoints < 3) return(generateFuzzySet(leftX, rightX, sFunctionDefaultNumPoints));
        else                     return(generateFuzzySet(leftX, rightX, defaultNumPoints));
    }

    /**
     * Creates a FuzzySet with an S-shape such that the membership value is
     * 0 at the leftX value and 1 at the rightX value. The number of points in
     * the generated FuzzySet is determined by the the paramter numberOfPoints
     * if it is acceptable (>= 3) or it is set to 3. If the number is even it will be set
     * to the next higher odd value (to maintain symmetry for the S curve).
     * 
     * @param leftX  the bottom left x value of the S-shaped curve.
     * @param rightX the upper right x value of the S-shaped curve.
     * @param numberOfPoints the number of points to be used when generating the 
     *               S-shaped curve.
     */
    public FuzzySet generateFuzzySet(double leftX, double rightX, int numberOfPoints)
    {
        double deltaX, X;
        double flexPoint = (leftX + rightX)/2;
        int numPoints = returnCorrectedNumPoints(numberOfPoints);
        int middle = numPoints/2;

        FuzzySet fs = new FuzzySet(numPoints);
        fs.numPoints = numPoints;

        fs.set[0] = new SetPoint( leftX, 0.0 );

        X = deltaX = (rightX - leftX) / (numPoints-1);
        for(int i=1; i<middle; i++){
            fs.set[i] = new SetPoint(leftX + X, sMembership(leftX + X, leftX, flexPoint, rightX));
            X += deltaX;
        }

        fs.set[middle] = new SetPoint( flexPoint, 0.5 );
        X = deltaX;

        for(int i=(middle + 1); i<numPoints-1; i++){
            fs.set[i] = new SetPoint(flexPoint + X, sMembership(flexPoint + X, leftX, flexPoint, rightX));
            X += deltaX;
        }

        fs.set[numPoints-1] = new SetPoint(rightX, 1.0);
        fs.simplifySet();
        return(fs);
    }

    /**
     * Calculates a membership value for an X value in the S-shaped function.
     *
     * @param x         the x value at which we want to get the membership value
     * @param leftX     the leftmost X value of the S-shaped curve
     * @param flexPoint the point of flex (symmetry) for the curve
     * @param rightX    the rightmost X value of the S-shaped curve
     */
    protected static double sMembership(double x, double leftX, double flexPoint, double rightX)
    {
        if(x <= leftX)                       return(0.0);
        else if(leftX < x && x < flexPoint)  return(2*sqr(((x - leftX)/(rightX - leftX))));
        else if(x == flexPoint)              return(0.5);
        else if(flexPoint < x && x < rightX) return(1 - 2*sqr(((x - rightX)/(rightX - leftX))));
        else                                 return(1.0);
    }


    /*=====================================
     *
     * STATIC CONTROL METHODS
     *
     *===================================*/

    /**
     * Sets the value of the defaultNumPoints variable.
     * This value is used to determine the number of points that will be
     * in the S-shaped fuzzy set generated by the 
     * <code>generateFuzzySet(double leftX, double rightX)</code> method,
     * unless it has a value of < 3, in which case the value of static (class)
     * variable, sFunctionDefaultNumPoints, will be used. This allows 
     * each instance of the SFunction to determine its own value for the number
     * of points to be generated. Initially it is set to have the value 0 so
     * that the sFunctionDefaultNumPoints value is used. If the number 
     * is even it will be set to the next higher odd value 
     * (to maintain symmetry for the S curve).
     */
    public void setNumPoints(int numPoints)
    {
        if(numPoints < 3)               defaultNumPoints = 3;
        else if((numPoints % 2) != 1)   defaultNumPoints = numPoints + 1;
        else                            defaultNumPoints = numPoints;
    }

    /**
     * Sets the value of the sFunctionDefaultNumPoints static (class) variable.
     * This value is used to determine the number of points that will be
     * in the S-shaped fuzzy set generated by the 
     * <code>generateFuzzySet(double leftX, double rightX)</code> method
     * when the local instance variable defaultNumPoints has not been
     * set or is < 3. Initially it is set to have the value 9. If the number 
     * is even it will be set to the next higher odd value 
     * (to maintain symmetry for the S curve).
     * 
     */

    public static void setDefaultNumberOfPoints(int numPoints)
    {
        if(numPoints < 3)               sFunctionDefaultNumPoints = 3;
        else if((numPoints % 2) != 1)   sFunctionDefaultNumPoints = numPoints + 1;
        else                            sFunctionDefaultNumPoints = numPoints;
    }


    /*=========================================
     *
     * METHODS TO MAKE LIFE A LITTLE EASIER
     *
     *=======================================*/

    /** 
     * Squares a double value.
     *
     * @param value the value to be squared.
     * 
     */
    protected static double sqr(double value)
    {
        return(value * value);
    }

    /** 
     * Keeps the values for the number of points in the S-shaped curve to
     * be >= 3 and odd.
     *
     * @param numPoints the integer value to be constrained to be >= 3 and odd.
     * 
     */
    protected int returnCorrectedNumPoints(int numPoints)
    {
        if(numPoints < 3)        return(3);
        if((numPoints % 2) != 1) return(numPoints+1);

        return(numPoints);
    }
}