/*
	A basic extension of the java.applet.Applet class
 */
package examples.fuzzyshower;

import java.awt.*;
import java.applet.*;

public class FuzzyShowerApplet extends Applet
{
	public void init()
	{
		// Take out this line if you don't use symantec.itools.net.RelativeURL or symantec.itools.awt.util.StatusScroller
		symantec.itools.lang.Context.setApplet(this);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setLayout(new GridLayout(1,3,10,10));
		setSize(156,49);
		startDemoButton.setLabel("Start Fuzzy Shower Demo");
		add(startDemoButton);
		startDemoButton.setBackground(java.awt.Color.lightGray);
		startDemoButton.setBounds(0,0,156,49);
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		startDemoButton.addActionListener(lSymAction);
		//}}
	}
	
	//{{DECLARE_CONTROLS
	java.awt.Button startDemoButton = new java.awt.Button();
	//}}

	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == startDemoButton)
				startDemoButton_ActionPerformed(event);
		}
	}

	void startDemoButton_ActionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
		ShowerFrame sf = new ShowerFrame("");
		sf.setVisible(true);
	    sf.inferenceCycleResults = new InferenceCycleFrame();
	    sf.showerSimulator = new ShowerSimulate(sf);
	    sf.showerSimulator.initSliders();
		sf.repaint();
	}
}
